/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "trirpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

tri_type *
class_tri_1(triangle arg1,  CLIENT *clnt)
{
	static tri_type clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CLASS_TRI,
		(xdrproc_t) xdr_triangle, (caddr_t) &arg1,
		(xdrproc_t) xdr_tri_type, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
