/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRIRPC_H_RPCGEN
#define _TRIRPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct triangle {
	int x;
	int y;
	int z;
};
typedef struct triangle triangle;

struct tri_type {
	int type;
	float area;
};
typedef struct tri_type tri_type;

#define CLASSIFY 0x20141308
#define TRI_SERVER_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define CLASS_TRI 1
extern  tri_type * class_tri_1(triangle , CLIENT *);
extern  tri_type * class_tri_1_svc(triangle , struct svc_req *);
extern int classify_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CLASS_TRI 1
extern  tri_type * class_tri_1();
extern  tri_type * class_tri_1_svc();
extern int classify_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_triangle (XDR *, triangle*);
extern  bool_t xdr_tri_type (XDR *, tri_type*);

#else /* K&R C */
extern bool_t xdr_triangle ();
extern bool_t xdr_tri_type ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRIRPC_H_RPCGEN */
