/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "trirpc.h"

bool_t
xdr_triangle (XDR *xdrs, triangle *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tri_type (XDR *xdrs, tri_type *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->area))
		 return FALSE;
	return TRUE;
}
